default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: ecomm_db

test:
  <<: *default
  database: ecomm_db_test

production:
  <<: *default
  database: ecomm_production
  username: <%= ENV['root'] %>
  password: <%= ENV['root'] %>
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
